#!/bin/bash

echo "# generated by $0"
ua_header="<browser_name>:<browser_version>:<os_platform>:<os_name>:<os_version>:<device_type>:<quirks>"
req_header="<tls_version>:<cipher_suites>:<extension_names>:<curves>:<ec_point_fmts>:<http_headers>:<quirks>"
mitm_header="<mitm_name>:<mitm_type>:<mitm_grade>"
echo "# ${ua_header}|${req_header}|${mitm_header}"

pcaps=`find reference_fingerprints/pcaps/browsers -type f -name "handshake.pcap"`
for pcapfile in $pcaps; do
	scripts/filename_to_fingerprint.py $pcapfile
done
